### ISSUE TITLE
Логическая ошибка в алгоритме операции пополнения кредитной карты

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#1]
## Описание
При условии, когда сумма пополнения кредитной карты (amount) больше нуля, после применения метода **add**,  баланс (balance) всегда равен сумме пополнения (amount). 

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/67b8d3873f127152cd3fc3b99df6b6b388b3ba59/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L76-L83

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **CreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - AddWithPositiveBalanceTest
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 2_000
creditLimit (кредитный лимит) = 6_000
rate (ставка) = 15
5. Вызвать метод пополнения кредитной карты **add** на сумму 3_000.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Баланс счёта (Balance) - 5_000 руб
Фактический результат : Баланс счёта (Balance) - 3_000 руб

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/67b8d3873f127152cd3fc3b99df6b6b388b3ba59/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L10-L19
## Скриншот 
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/62ec5f34-651c-4696-89dc-a443a3f65094)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Способ решения**

В классе **CreditAccount**, в строке условия **If**, исправить строку **balance = amount** на **balance = balance + amount**

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в класс **CreditAccount**, метод add
3. Изменить строку **balance = amount** на **balance = balance + amount**
4. Перейти в тестовый класс **CreditAccountTest** 
5. Запустить с прежними данными  тест **AddWithPositiveBalanceTest**
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/07d67100-4247-409d-a701-9f13ae51f9b2)
