### ISSUE TITLE
Отсутствует исключения при вводе некорректных данных (minBalance > maxBalance)

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#11]
## Описание
При проверке исключения на ввод некорректных данных (minBalance > maxBalance) тест не проходит. Исключение отсутствует

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/main/java/ru/netology/javaqadiplom/IllegalArgumentException.java#L1-L7

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/c4d08dfaa0a40601c1fbd615ddd1cd31ed8e5089/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки исключения на ввод начального баланса меньше минимального баланса - shouldExceptionWhenMinBalanceLessZero
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = 6_000
minBalance (минимальный баланс) = 15_000
maxBalance (максимальный баланс) = 10_000
rate (ставка) = 10
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Зеленый тест
Фактический результат : Красный тест, ошибка типа: Expected ru.netology.javaqadiplom.IllegalArgumentException to be thrown, but nothing was thrown.

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L286-L294

## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/910ebc4f-fedc-402f-9861-293fb2f90295)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## **Способ решения**
Решение путём включения в конструктор класса **SavingAccount** проверки условия **minBalance<=maxbalance**. В случае когда **minBalance>maxBalanсe**  появляется исключение типа **IllegalArgumentException.**

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L111) в IDEA
2. Перейти в класс **SavingAccount**
3. Конструктор класса дополнить строками кода:

https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/ed4081a914b932339a2b13e4c6331bd6b4c091dc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L48
4. Перейти в тестовый класс **SavingAccountTest**
5. Запустить с прежними данными тест shouldExceptionWhenMinBalanceMoreMaxBalance
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/840a8049-3798-4ea6-a280-f47d918d45a0)


Ожидаемый результат : true
Фактический результат : true (ошибка соответствует IllegalArgumentException типу)
