### ISSUE TITLE
Ошибка в логике  метода покупки pay

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#12]
## Описание
При применении метода покупки (pay) присутствует логическая ошибка. При условии положительного первоначального баланса и покупки на меньшую сумму, ожидаемый результат не соответствует фактическому. 

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/2e4c8aa32c7665192e775694c1a6828973f3b6aa/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **reditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - payPositiveBalanceTest
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 5_000
creditLimit (кредитный лимит) = 6_000
rate (ставка) = 5
5. Вызвать метод покупки по карте - pay на сумму 2000 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Баланс - 3000 руб
Фактический результат : Проценты - (-2000) руб

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/f563a583e55e5723a021d599f9d021373b7c811f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L78-L87

## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/8dd6b3c3-904f-4cca-8288-04130365eb19)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Способ решения**

В классе **CreditAccount**, в методе **pay**, перенести условие **balance = balance - amount** после проверки баланса, строку **balance = -amount** удалить. Также изменить условие **>creditLimit**
## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в класс **CreditAccount**, метод pay
3. Перенести условие **balance = balance - amount** после проверки баланса, строку **balance = -amount** удалить. Также изменить условие **balance > -creditLimit** на **balance - amount >= -creditLimit**
4. Перейти в тестовый класс **CreditAccountTest** 
5. Запустить с прежними данными  тест **AddWithPositiveBalanceTest**
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/e75d18bf-b57c-412f-a3fc-a4961f5032b7)
