### ISSUE TITLE
Превышение кредитного лимита в методе покупки pay

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#13]
## Описание
При применении метода покупки (pay) присутствует логическая ошибка.  При условии превышения значения баланса над кредитным лимитом,  метод возвращает true (фактическое), а должен false (ожидаемое).

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/2e4c8aa32c7665192e775694c1a6828973f3b6aa/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **сreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - **payBalanceLessThanLimitTest**
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 2_000
creditLimit (кредитный лимит) = 5_000
rate (ставка) = 5
5. Вызвать метод покупки по карте - pay на сумму 8000 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : false
Фактический результат : true

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/f563a583e55e5723a021d599f9d021373b7c811f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L111-L118

## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/9b62b081-57d1-4e20-a4d1-5fa3fe43aff3)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Шаги исправления**
Было исправлено в Issue #12 
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/0e657926-de09-4358-a5e7-44d9792468e3)
