### ISSUE TITLE
Равенство кредитного лимита и баланса приводит к ошибке в методе pay

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#14]
## Описание
При условии, когда баланс , после применения метода pay, будет равен кредитному лимиту, метод pay возвращает false. Ожидаемый результат - true.

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/2e4c8aa32c7665192e775694c1a6828973f3b6aa/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **сreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - **payBalanceEqualsCreditLimitTest**
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 2_000
creditLimit (кредитный лимит) = 5_000
rate (ставка) = 5
5. Вызвать метод покупки по карте - pay на сумму 7000 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : true
Фактический результат : false

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/f563a583e55e5723a021d599f9d021373b7c811f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L99-L109
## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/ae97dfa1-b587-41c5-8e7e-9461e2db53aa)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Шаги исправления**
Было исправлено в Issue #12 
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/e0b9990e-0e44-4a6c-87d6-8f6f17eb3f11)
