### ISSUE TITLE
Параметр кредитный лимит не имеет исключения на отрицательное значение

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#16]
## Описание
Отсутствует проверка параметра кредитный лимит на предмет ошибочного ввода отрицательного значения. 
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/2e4c8aa32c7665192e775694c1a6828973f3b6aa/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L17

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/2e4c8aa32c7665192e775694c1a6828973f3b6aa/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L29

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **сreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - **IllegalArgumentExceptionCreditLimitTest**
4. Создать **объект класса CreditAccount** 
5. Написать проверку на появление исключения IllegalArgumentException, в случает отрицательного CreditLimit.
6. Передать в строке Assertions объект класса CreditAccount с заполненными полями:

initialBalance (начальный баланс) =1_000
creditLimit (кредитный лимит) = -10_000
rate (ставка) = 15

7.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : true
Фактический результат : false

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/f563a583e55e5723a021d599f9d021373b7c811f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L142-L146
## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/b9f31445-bb3c-4a81-9762-45123e395308)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Способ решения**

В классе **CreditAccount** добавить исключение на ввод некорректного значения кредитного лимита.
## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в класс **CreditAccount**
3. Добавить исключение в виде: 
*if (creditLimit < 0) {
            throw new IllegalArgumentException(
                    "Кредитный лимит не может быть отрицательным, а у вас: " + creditLimit
            );
        }*
5. Перейти в тестовый класс **CreditAccountTest** 
6. Запустить с прежними данными  тест **IllegalArgumentExceptionCreditLimitTest**
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/ee3cecac-c287-4961-aaa2-864c382bbf99)
