### ISSUE TITLE
Начисление процентов на положительный баланс кредитной карты

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#2]
## Описание
Метод начисления процентов на отрицательный баланс кредитной карты **yearChange** начисляет проценты и в случае положительного баланса кредитной карты
## Условие
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/459de109bf199a8b9ef814feae1b7edd7268338e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L78

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/459de109bf199a8b9ef814feae1b7edd7268338e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L84

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **CreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - yearChangePositiveBalanceTest
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 1_000
creditLimit (кредитный лимит) = 6_000
rate (ставка) = 10
5. Вызвать метод покупки по карте - pay на сумму 500 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Проценты - 0 руб
Фактический результат : Проценты - (-50) руб

## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/d1e3efa3-d138-4447-a49e-8a44de2cc0fd)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Способ решения**

В классе **CreditAccount**, в методе **yearChange** добавить условие проверки баланса.

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в класс **CreditAccount**, метод **yearChange**
3. Добавить условие проверки: **if (balance >= -creditLimit && balance<0) {**
5. Перейти в тестовый класс **CreditAccountTest** 
6. Запустить с прежними данными  тест **yearChangePositiveBalanceTest**
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/ccd384bd-c5da-4bc4-a02c-1c18b6123f21)
