### ISSUE TITLE
Начисление процентов на отрицательный баланс сберегательного счета

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#3]
## Описание
Метод начисления процентов на положительный баланс сберегательного счета **yearChange** начисляет проценты в случае отрицательного баланса сберегательного счета

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/d780f5741f9195a9caa9c4e4b1a1bfd9ea51d6ee/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/c4d08dfaa0a40601c1fbd615ddd1cd31ed8e5089/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки операции начисления процентов на остаток баланса - shouldYearChangeOnNegativeBalance
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = -200
minBalance (минимальный баланс) = 0
maxBalance (максимальный баланс) = 10_000
rate (ставка) = 15
5.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Начислено - 0
Фактический результат : Начислено -  -30

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/90aa70eef43e313dd72f8480994db932f2596252/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L186-L199

## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/46483bb0-51f9-4c81-8a94-93f5754efe5b)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## **Способ решения**

Решение путём включения в конструктор класса SavingAccount проверки на положительное  значение  для поля InitialBalance. В случае отрицательного значения - появляется исключение типаIllegalArgumentException.

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в класс **SavingAccount**
3. Конструктор класса дополнить строками кода:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3de3faa312a05fdc15d0ab56878af1beb46ac1e0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L29-L33
4. Перейти в тестовый класс **SavingAccountTest** 
5. Запустить с прежними данными  тест **shouldYearChangeOnNegativeBalance**
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/2442d734-6a21-4108-bca9-e8519b6fc07b)

Ожидаемый результат : Начислено - 0
Фактический результат : Начислено - 0 (появляется исключение типа IllegalArgumentException)
