### ISSUE TITLE
Не верный алгоритм подсчёт процентов по карте на отрицательный счёт кредитной карты

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#4]
## Описание
Метод начисления процентов на отрицательный баланс кредитной карты **yearChange** начисляет проценты с ошибкой в вычислениях.

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/459de109bf199a8b9ef814feae1b7edd7268338e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L84

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **CreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - yearChangeNegativeBalanceTest
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 1_000
creditLimit (кредитный лимит) = 6_000
rate (ставка) = 10
5. Вызвать метод покупки по карте - pay на сумму 2000 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Проценты - (-100) руб
Фактический результат : Проценты - (-200) руб

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/76a36c339ea37eeb36d91094af4d989ee165f648/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L43-L52
## Скриншот

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/a36d03e6-fc69-414e-8690-e048dec8dec1)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Шаги исправления**
Было исправлено в Issue #2.
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/ebfba042-c75b-42fa-9e5d-f42586ab4254)
