### ISSUE TITLE
Метод начисления процентов начисляет проценты на баланс меньше кредитного лимита..

### ISSUE THREAD

**Issue by Kozyavin** [Kozyavin/JAVAQA63-TEAM-DIPLOM#5]
## Описание
Метод начисления процентов на отрицательный баланс кредитной карты начисляет проценты на баланс меньше кредитного лимита.

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/21b08f381e3f6476c9068c9b0ed11f215f6c532d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L86-L88

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Перейти в тестовый класс **CreditAccountTest**
3. Создать тест проверки операции пополнения кредитной карты - yearChangeMoreCreditLimitBalanceTest
4. Создать **объект класса CreditAccount** и внести начальные данные :
initialBalance (начальный баланс) = 1_000
creditLimit (кредитный лимит) = 6_000
rate (ставка) = 5
5. Вызвать метод покупки по карте - pay на сумму 8000 руб.
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Проценты - 0 руб
Фактический результат : Проценты - (-350) руб

## Тест
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/f563a583e55e5723a021d599f9d021373b7c811f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L66-L75
## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/5b5375a5-163d-495b-9b7f-20c1932f6c1f)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by ArtemKoliukh** [comment]
## **Шаги исправления**
Было исправлено в Issue #2.
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/68ae285e-4992-4594-9b87-78720f474d5c)
