### ISSUE TITLE
Некорректный вывод баланса при вызове метода "add"

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#6]
## Описание
При реализации метода пополнения, итоговый баланс становится равен цене покупки.

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/08f599c2e963fc60f0f2bead54e11c79861d10e1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70-L80

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/tree/saving/src/test/java/ru/netology/javaqadiplom) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки операции пополнения сберегательного счета - shouldAdd.
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = 2_000
minBalance (минимальный баланс) = 1_000
maxBalance (максимальный баланс) = 10_000
rate (ставка) = 15
amount = 3_000
5.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : 5_000
Фактический результат : 3_000

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/08f599c2e963fc60f0f2bead54e11c79861d10e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20

## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/79edda96-d7bf-450b-bb31-27a43f916780)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## **Способ решения**
Метод add имеет ошибку при вычислении баланса после покупки. Нужно исправить алгоритм вычисления метода пополнения баланса.
## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в класс **SavingAccount**
3. Внести изменения в коде метода **add**: 
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/d8a2fb344758cdd49022252c19ce46638a38265d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L75-L85
4. Перейти в тестовый класс **SavingAccountTest**
5. Запустить с прежними данными тест **shouldAdd**

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/339e8f80-d2c2-4570-9815-2bc3f91f9fbe)

Ожидаемый результат : Баланс - 5_000 руб
Фактический результат : Баланс - 5_000 руб
