### ISSUE TITLE
Отсутствует исключение при вводе отрицательного начального баланса

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#7]
## Описание
При проверке исключения на ввод отрицательного начального баланса тест не проходит. Исключение отсутствует

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/main/java/ru/netology/javaqadiplom/IllegalArgumentException.java#L1-L7

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/c4d08dfaa0a40601c1fbd615ddd1cd31ed8e5089/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки исключения на ввод отрицательного начального баланса - shouldExceptionWhenBalanceLessZero
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = -1_000
minBalance (минимальный баланс) = 1_000
maxBalance (максимальный баланс) = 15_000
rate (ставка) = 10
5.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Зеленый тест
Фактический результат : Красный тест, ошибка типа: Expected ru.netology.javaqadiplom.IllegalArgumentException to be thrown, but nothing was thrown.

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L250-L257
## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/cc934de6-e28c-483f-8102-948d3449e2a3)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## **Способ решения**
Решение путём включения в конструктор класса SavingAccount проверки на положительное значение для поля InitialBalance. В случае отрицательного значения - появляется исключение типаIllegalArgumentException.

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в класс **SavingAccount**
3. Конструктор класса дополнить строками кода:

https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/d8a2fb344758cdd49022252c19ce46638a38265d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L29-L32
4. Перейти в тестовый класс **SavingAccountTest**
5. Запустить с прежними данными тест **shouldExceptionWhenBalanceLessZero**

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/fcc628c7-d896-4bb5-a4d8-3dc16b6e4e67)

Ожидаемый результат : true
Фактический результат : true (ошибка соответствует IllegalArgumentException типу)
