### ISSUE TITLE
Отсутствует исключение при вводе некорректного начального баланса (меньше minBalance)

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#8]
## Описание
При проверке исключения на ввод начального баланса меньше минимального, тест не проходит. Исключение отсутствует

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/main/java/ru/netology/javaqadiplom/IllegalArgumentException.java#L1-L7

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/c4d08dfaa0a40601c1fbd615ddd1cd31ed8e5089/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки исключения на ввод начального баланса меньше минимального баланса - shouldExceptionWhenBalanceLessMinBalance
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = 500
minBalance (минимальный баланс) = 1_000
maxBalance (максимальный баланс) = 15_000
rate (ставка) = 10
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Зеленый тест
Фактический результат : Красный тест, ошибка типа: Expected ru.netology.javaqadiplom.IllegalArgumentException to be thrown, but nothing was thrown.

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L259-L266
## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/f745a88b-424f-451b-916a-8a204a1ebece)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## Способ решения
Решение путём включения в конструктор класса SavingAccount проверки условия  **minBalance<=initialBalance<=maxBalance**. В случае не соответствия значения баланса данному диапазону  - появляется исключение типа IllegalArgumentException.

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L111) в IDEA
2. Перейти в класс **SavingAccount**
3. Конструктор класса дополнить строками кода:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/acb063b5421c51637b93c0325dbb33855d98a891/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L34-L37
5. Перейти в тестовый класс **SavingAccountTest**
6. Запустить с прежними данными тест **shouldExceptionWhenBalanceLessMinBalance**

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/d27ce976-87bb-463e-811c-76f7fe75ba87)


Ожидаемый результат : true
Фактический результат : true (ошибка соответствует IllegalArgumentException типу)
