### ISSUE TITLE
Отсутствует исключение при вводе некорректного начального баланса (больше maxBalance)

### ISSUE THREAD

**Issue by ArtemKoliukh** [Kozyavin/JAVAQA63-TEAM-DIPLOM#9]
## Описание
При проверке исключения на ввод начального баланса больше максимального баланса, тест не проходит. Исключение отсутствует

## Локация дефекта
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/main/java/ru/netology/javaqadiplom/IllegalArgumentException.java#L1-L7

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/c4d08dfaa0a40601c1fbd615ddd1cd31ed8e5089/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Перейти в тестовый класс **SavingAccountTest**
3. Создать тест проверки исключения на ввод начального баланса меньше минимального баланса - shouldExceptionWhenBalanceMoreMaxBalance
4. Создать **объект класса SavingAccount** и внести начальные данные :
initialBalance (начальный баланс) = 20_000
minBalance (минимальный баланс) = 1_000
maxBalance (максимальный баланс) = 15_000
rate (ставка) = 10
6.  Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Зеленый тест
Фактический результат : Красный тест, ошибка типа: Expected ru.netology.javaqadiplom.IllegalArgumentException to be thrown, but nothing was thrown.

## Test:
https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/3bec6280231defbf6276881d4201bd875c125911/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L268-L275
## Скриншот
![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/131406375/cdb655e4-5aba-468f-9373-4983106fba21)

## Окружение

- Операционная система : Windows 10 Pro
- Окружение : IntelliJ IDIA 2022.3.1
- JAVA : OpenJDK11

**Comment by Kozyavin** [comment]
## **Способ решения**
Решение путём включения в конструктор класса **SavingAccount** проверки условия minBalance<=initialBalance<=maxBalance. В случае не соответствия значения баланса данному диапазону - появляется исключение типа IllegalArgumentException.

## **Шаги решения**
1. Открыть [код программы](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L111) в IDEA
2. Перейти в класс SavingAccount
3. Конструктор класса дополнить строками кода:

https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/blob/acb063b5421c51637b93c0325dbb33855d98a891/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L34-L37
4. Перейти в тестовый класс **SavingAccountTest**
5. Запустить с прежними данными тест **shouldExceptionWhenBalanceMoreMaxBalance**

![image](https://github.com/Kozyavin/JAVAQA63-TEAM-DIPLOM/assets/127535915/bc650279-e908-4a9c-9ff8-e3a8b4fc6ca2)


Ожидаемый результат : true
Фактический результат : true (ошибка соответствует IllegalArgumentException типу)
